version: "3"
services:
  invoices:
    container_name: ms-invoices
    image: 'ms-invoices:latest'
    network_mode: bridge
    restart: always
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile
    ports:
      - "9060:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'test'
      SPRING_CLOUD_CONFIG_URI: '<url>'
      SPRING_CLOUD_CONFIG_USERNAME: '<username>'
      SPRING_CLOUD_CONFIG_PASSWORD: '<password>'
